name: Rust Pipeline

on:
  workflow_dispatch:

  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Build
        run: |
          cd examples/1-crawl
          cargo fmt
          cargo build --verbose
      - name: Run tests
        run: |
          cd examples/1-crawl
          cargo test --verbose
